config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :lists

  resources :users do
    get 'lists', on: :member
  end

  resources :purchases do
    post 'toggle_bought', on: :collection
    get 'last', on: :collection
  end

  resource :session, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'login', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post 'application/toggle_maintenance', to: 'application#toggle_maintenance'

  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :lists, dependent: :destroy
  has_many :user_log_in, dependent: :destroy
  has_many :owner_friendship_requests, :class_name => "FriendshipRequest", :foreign_key => "owner_id", dependent: :destroy
  has_many :target_friendship_requests, :class_name => "FriendshipRequest", :foreign_key => "target_id", dependent: :destroy

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :username, presence: true, uniqueness: true
  # Ei toiminut Herokussa:
  # validates :email, email: true
  validate :password_validation

  def password_validation
    unless password.match(/[A-Z]/) and password.match(/[[:digit:]]/) and password.length > 7
      errors.add(:password, "The password needs to contain at least one digit and one capital letter, and the minimum password length is eight characters.")
    end
  end

  def get_available
    if UserLogIn.logged_in.find_by(user_id: id)
      true
    else
      false
    end
  end

  def get_last_signin
    logins = UserLogIn.where(user_id: id).order(created_at: :desc)

    unless logins.empty?
      logins.first.created_at
    else
      Time.new(1900)
    end
  end

  def get_last_seen
    logins = UserLogIn.where(user_id: id).order(created_at: :desc)

    unless logins.empty?
      logins.first.logout_time
    else
      Time.new(1900)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :lists]
  before_action :check_service

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.joined = DateTime.now
    @user.admin = false

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        UserLogIn.create(user: @user)
        format.html { redirect_to @user, notice: "Welcome #{@user.first_name}!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def lists
    @lists = List.where user: @user
    @list = List.new user: @user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :username, :email, :joined, :last_signin, :available, :password_digest)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Available</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.get_available %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/lists.html.erb
<h1><%= @user.username %>'s Shopping Lists</h1>

<p>
  <strong>Add a new list!</strong>
</p>
<%= form_for @list do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h4>Lists:</h4>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.username %></h1>
<% if @user.admin? %>
  <h5>Administrator</h5>
<% end %>

<% if @user.get_available %>
    <p><strong>Available now!</strong></p>
<% else %>
    <p><strong>Last seen:</strong> <%= get_nice_time_str(@user.get_last_seen) %></p>
<% end %>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Joined:</strong>
  <%= get_nice_time_str(@user.created_at) %>
</p>

<p>
  <strong><%= link_to "Lists", lists_user_path(@user) %></strong>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>