config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :lists

  resources :users do
    get 'lists', on: :member
  end

  resources :purchases do
    post 'toggle_bought', on: :collection
    get 'last', on: :collection
  end

  resource :session, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'login', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post 'application/toggle_maintenance', to: 'application#toggle_maintenance'

  root 'sessions#new'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<% if !are_we_open and current_user and ensure_admin %>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #ffff00">
<% else %>
<nav class="navbar navbar-inverse navbar-fixed-top">
<% end %>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>
    <li><%= link_to "My lists", lists_user_path(current_user) %></li>
<% end %>
<% if current_user and current_user.admin %>
    <li><%= link_to 'Products', products_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Toggle maintenance mode', 'application/toggle_maintenance', :method => :post %></li>
<% end %>
<% if current_user %>
    <li><%= link_to current_user.username, current_user %></li>
    <li><%= link_to 'Sign out', signout_path, :method => :delete %></li>
<% else %>
    <li><%= link_to 'Sign in', signin_path %></li>
    <li><%= link_to 'Sign up', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shopping List" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Shopping List" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>